thesis:
	latexmk -xelatex -f -interaction=nonstopmode DeepPR

translation:
	latexmk -xelatex -f -interaction=nonstopmode Translation

presentation:
	latexmk -xelatex -f -interaction=nonstopmode Presentation

clean:
	rm -f *.toc *.bbl *.blg *.out *.aux *.log *.bak *.thm *.synctex.gz *.fdb_latexmk *.fls *.glo *.gls *.idx *.ilg *.ind
